---
name: ez_ticketz_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  time: ^2.1.0
  cached_network_image: ^3.2.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  google_fonts: ^2.2.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  flutter_launcher_icons: ^0.9.2
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  shared_preferences: ^2.0.12
  sliding_up_panel: ^2.0.0+1
  intl: ^0.17.0
  dartdoc: ^4.1.0
  better_player: ^0.0.81
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^5.0.2
  clock: ^1.1.0
  mockito: ^5.0.17
  golden_toolkit: ^0.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  build_runner: null
  flutter_native_splash: ^1.3.3
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
  - assets/
  - google_fonts/
flutter_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
flutter_native_splash:
  color: '#141414'
  image: assets/app_icon.png
  ios: false
  web: false
