---
name: ez_ticketz_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.3
  time: ^2.0.0
  cached_network_image: ^3.1.0
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  flutter_launcher_icons: ^0.9.1
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  intl: ^0.17.0
  dartdoc: ^1.0.0
  better_player: ^0.0.72
  flutter_spinkit: 5.0.0
  flutter_secure_storage: ^4.2.1
  clock: ^1.1.0
  mockito: ^5.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  build_runner: null
  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
  - assets/
flutter_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
flutter_native_splash:
  color: '#141414'
  image: assets/app_icon.png
  ios: false
  web: false
