name: Test PR and Push
on:
  pull_request:
    branches: [release,dev,master]
    paths-ignore: ['doc/**','**.md','.gitignore','Prototype/**']
  push:
    branches: [feature/**,hotfix/**]
    paths-ignore: ['doc/**','**.md','.gitignore','Prototype/**']
jobs:
  build:
    name: Test APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Checkout Flutter Stable Channel
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Get Pub Dependencies
      run: flutter pub get
    - name: Run build runner for codegen files
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
    - name: Run Dart Analyzer
      run: flutter analyze .
    - name: Attempt release build generation
      run: flutter build apk --target-platform android-arm,android-arm64 --obfuscate --split-debug-info=./ez_tickets_app/debug_trace